core = "7.x"
api = "2"

projects[google_analytics][subdir] = "contrib"
projects[metatag][subdir] = "contrib"
projects[transliteration][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"
projects[redirect][subdir] = "contrib"
projects[seo_ui][subdir] = "contrib"
projects[seo_ui][patch][] = "https://www.drupal.org/files/1394342_fix-undefined-indices_15.patch"